INSERT INTO Projects (name, description, info, imgpath, url)
VALUES ("BJ's Tattoo Haven", "A white label webpage for tattoo parlors and other services that require booking.", "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Culpa debitis ducimus tempore cumque unde delectus! Magni iste illo voluptatum ipsa? Quia earum officiis alias delectus odio totam dicta consectetur ipsum! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quis, minus! Provident, ex? Ut est accusantium hic praesentium itaque iste, voluptates voluptatem ipsam culpa tempore velit facilis, ratione eum pariatur dolor.Lorem ipsum, dolor sit amet consectetur adipisicing elit. Culpa debitis ducimus tempore cumque unde delectus! Magni iste illo voluptatum ipsa? Quia earum officiis alias delectus odio totam dicta consectetur ipsum! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quis, minus! Provident, ex? Ut est accusantium hic praesentium itaque iste, voluptates voluptatem ipsam culpa tempore velit facilis, ratione eum pariatur dolor.", "/bjtattoo.jpg", "https://github.com/thispastwinter/tattoo-haven");

INSERT INTO Projects (name, description, info, imgpath, url)
VALUES ("Batch Calculator", "A calculator designed for bars who need to convert single serving recipes to larger batches.", "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Culpa debitis ducimus tempore cumque unde delectus! Magni iste illo voluptatum ipsa? Quia earum officiis alias delectus odio totam dicta consectetur ipsum! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quis, minus! Provident, ex? Ut est accusantium hic praesentium itaque iste, voluptates voluptatem ipsam culpa tempore velit facilis, ratione eum pariatur dolor.Lorem ipsum, dolor sit amet consectetur adipisicing elit. Culpa debitis ducimus tempore cumque unde delectus! Magni iste illo voluptatum ipsa? Quia earum officiis alias delectus odio totam dicta consectetur ipsum! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quis, minus! Provident, ex? Ut est accusantium hic praesentium itaque iste, voluptates voluptatem ipsam culpa tempore velit facilis, ratione eum pariatur dolor.", "/batchcalc.jpg", "https://github.com/thispastwinter/batchcalculator");

INSERT INTO Projects (name, description, info, imgpath, url)
VALUES ("Caster", "A digital spell book for Dungeons and Dragons 5th Edition", "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Culpa debitis ducimus tempore cumque unde delectus! Magni iste illo voluptatum ipsa? Quia earum officiis alias delectus odio totam dicta consectetur ipsum! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quis, minus! Provident, ex? Ut est accusantium hic praesentium itaque iste, voluptates voluptatem ipsam culpa tempore velit facilis, ratione eum pariatur dolor.Lorem ipsum, dolor sit amet consectetur adipisicing elit. Culpa debitis ducimus tempore cumque unde delectus! Magni iste illo voluptatum ipsa? Quia earum officiis alias delectus odio totam dicta consectetur ipsum! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quis, minus! Provident, ex? Ut est accusantium hic praesentium itaque iste, voluptates voluptatem ipsam culpa tempore velit facilis, ratione eum pariatur dolor.", "/caster.jpg", "https://github.com/thispastwinter/project1");

INSERT INTO Projects (name, description, info, imgpath, url)
VALUES ("Bamazon", "A CLI based app that emulates an online ordering platform using Node.js.", "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Culpa debitis ducimus tempore cumque unde delectus! Magni iste illo voluptatum ipsa? Quia earum officiis alias delectus odio totam dicta consectetur ipsum! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quis, minus! Provident, ex? Ut est accusantium hic praesentium itaque iste, voluptates voluptatem ipsam culpa tempore velit facilis, ratione eum pariatur dolor.Lorem ipsum, dolor sit amet consectetur adipisicing elit. Culpa debitis ducimus tempore cumque unde delectus! Magni iste illo voluptatum ipsa? Quia earum officiis alias delectus odio totam dicta consectetur ipsum! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quis, minus! Provident, ex? Ut est accusantium hic praesentium itaque iste, voluptates voluptatem ipsam culpa tempore velit facilis, ratione eum pariatur dolor.", "/bamazon.gif", "https://github.com/thispastwinter/Bamazon");

